-- ============================================
-- KALEADS ATOMIC AGENTS - SUPABASE SCHEMA
-- ============================================
-- Ce schema crée toutes les tables nécessaires pour le système
-- À exécuter dans Supabase > SQL Editor
-- ============================================

-- ============================================
-- TABLE 1 : clients
-- ============================================
CREATE TABLE IF NOT EXISTS clients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_name TEXT NOT NULL UNIQUE,

  -- Context files (stored in Supabase Storage)
  pci_file_path TEXT,              -- Path: clients/{client_id}/pci.md
  personas_file_path TEXT,          -- Path: clients/{client_id}/personas.md
  pain_points_file_path TEXT,       -- Path: clients/{client_id}/pain_points.md
  competitors_file_path TEXT,       -- Path: clients/{client_id}/competitors.json
  case_studies_folder_path TEXT,    -- Path: clients/{client_id}/case_studies/

  -- Metadata
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_clients_active ON clients(active);

-- ============================================
-- TABLE 2 : templates
-- ============================================
CREATE TABLE IF NOT EXISTS templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  template_name TEXT NOT NULL UNIQUE,

  -- Template content (stored in Supabase Storage)
  template_file_path TEXT NOT NULL,  -- Path: templates/{template_id}/template.md

  -- Metadata
  strategy_type TEXT CHECK (strategy_type IN ('cold_email', 'linkedin', 'follow_up', 'break_up')),
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_templates_active ON templates(active);
CREATE INDEX IF NOT EXISTS idx_templates_strategy ON templates(strategy_type);

-- ============================================
-- TABLE 3 : contacts_to_enrich
-- ============================================
CREATE TABLE IF NOT EXISTS contacts_to_enrich (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Foreign keys
  client_id UUID REFERENCES clients(id) ON DELETE CASCADE,
  template_id UUID REFERENCES templates(id) ON DELETE SET NULL,

  -- Contact data
  first_name TEXT,
  last_name TEXT,
  email TEXT,
  company_name TEXT NOT NULL,
  website TEXT,
  linkedin_url TEXT,
  industry TEXT,

  -- Enrichment data (flexible JSON)
  enrichment_data JSONB DEFAULT '{}',

  -- Processing status
  status TEXT CHECK (status IN ('pending', 'enriching', 'completed', 'failed')) DEFAULT 'pending',
  error_message TEXT,

  -- Batch management
  batch_id UUID NOT NULL,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  processed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_contacts_status ON contacts_to_enrich(status);
CREATE INDEX IF NOT EXISTS idx_contacts_batch ON contacts_to_enrich(batch_id);
CREATE INDEX IF NOT EXISTS idx_contacts_client ON contacts_to_enrich(client_id);
CREATE INDEX IF NOT EXISTS idx_contacts_created_at ON contacts_to_enrich(created_at DESC);

-- ============================================
-- TABLE 4 : emails_generated
-- ============================================
CREATE TABLE IF NOT EXISTS emails_generated (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Foreign key
  contact_id UUID REFERENCES contacts_to_enrich(id) ON DELETE CASCADE,

  -- Email variables generated by agents
  hook TEXT,
  specific_signal_1 TEXT,
  specific_signal_2 TEXT,
  specific_target_1 TEXT,
  specific_target_2 TEXT,
  competitor_name TEXT,
  competitor_product_category TEXT,
  problem_specific TEXT,
  impact_measurable TEXT,
  target_persona TEXT,
  case_study_result TEXT,

  -- Composed email (final output)
  email_generated TEXT NOT NULL,
  email_final TEXT,  -- After manual editing if needed

  -- Quality metrics (flexible JSON for future extensions)
  quality_metrics JSONB DEFAULT '{}',

  -- Review workflow
  review_status TEXT CHECK (review_status IN (
    'pending_review',
    'approved',
    'approved_edited',
    'rejected',
    'sent'
  )) DEFAULT 'pending_review',

  reviewer_id UUID,
  reviewed_at TIMESTAMPTZ,

  rejection_reason TEXT CHECK (rejection_reason IN (
    'wrong_persona',
    'incorrect_competitor',
    'grammar_issues',
    'tone_too_corporate',
    'incorrect_info',
    'low_quality',
    'other'
  )),
  rejection_details TEXT,

  -- Smartlead/Instantly integration
  campaign_id TEXT,
  campaign_name TEXT,
  sequencer_lead_id TEXT,
  sent_at TIMESTAMPTZ,

  -- Metadata
  generation_time_ms INTEGER,
  tokens_used INTEGER,
  agent_version TEXT,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_emails_review_status ON emails_generated(review_status);
CREATE INDEX IF NOT EXISTS idx_emails_contact ON emails_generated(contact_id);
CREATE INDEX IF NOT EXISTS idx_emails_created_at ON emails_generated(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_emails_campaign ON emails_generated(campaign_id);

-- ============================================
-- TABLE 5 : review_analytics (Optional)
-- ============================================
CREATE TABLE IF NOT EXISTS review_analytics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Period tracking
  date DATE NOT NULL,
  client_id UUID REFERENCES clients(id),

  -- Metrics
  total_generated INTEGER DEFAULT 0,
  total_approved INTEGER DEFAULT 0,
  total_edited INTEGER DEFAULT 0,
  total_rejected INTEGER DEFAULT 0,

  approval_rate DECIMAL(5,2),
  edit_rate DECIMAL(5,2),
  rejection_rate DECIMAL(5,2),

  avg_review_time_seconds INTEGER,
  avg_quality_score DECIMAL(5,2),

  -- Top rejection reasons (JSON array)
  rejection_reasons_breakdown JSONB DEFAULT '[]',

  created_at TIMESTAMPTZ DEFAULT NOW(),

  -- Unique constraint: one record per day per client
  UNIQUE(date, client_id)
);

CREATE INDEX IF NOT EXISTS idx_analytics_date ON review_analytics(date DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_client ON review_analytics(client_id);

-- ============================================
-- TRIGGERS : Auto-update timestamps
-- ============================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_clients_updated_at ON clients;
CREATE TRIGGER update_clients_updated_at
  BEFORE UPDATE ON clients
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_templates_updated_at ON templates;
CREATE TRIGGER update_templates_updated_at
  BEFORE UPDATE ON templates
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_emails_updated_at ON emails_generated;
CREATE TRIGGER update_emails_updated_at
  BEFORE UPDATE ON emails_generated
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- ROW LEVEL SECURITY (RLS) - Multi-tenant
-- ============================================

-- Enable RLS on all tables
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts_to_enrich ENABLE ROW LEVEL SECURITY;
ALTER TABLE emails_generated ENABLE ROW LEVEL SECURITY;
ALTER TABLE review_analytics ENABLE ROW LEVEL SECURITY;

-- Example policies (À adapter selon vos besoins)
-- CREATE POLICY "Users can view their client's data" ON contacts_to_enrich
--   FOR SELECT
--   USING (client_id IN (
--     SELECT client_id FROM auth.users WHERE id = auth.uid()
--   ));

-- ============================================
-- SEED DATA (Optional - Pour tests)
-- ============================================

-- Insérer un client de test
INSERT INTO clients (client_name, active)
VALUES ('Test Client', true)
ON CONFLICT (client_name) DO NOTHING;

-- Insérer un template de test
INSERT INTO templates (template_name, template_file_path, strategy_type, active)
VALUES ('Cold Email V1', 'templates/cold_email_v1.md', 'cold_email', true)
ON CONFLICT (template_name) DO NOTHING;

-- ============================================
-- VÉRIFICATION
-- ============================================

-- Vérifier que toutes les tables sont créées
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;

-- Output attendu:
-- clients
-- contacts_to_enrich
-- emails_generated
-- review_analytics
-- templates
